import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import Header from "./_features/header/Header";
import Footer from "./_features/footer/Footer";
import ContextLayout from "./hooks/contextLayout";


const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Dulces Caprichos - Reposteria Creativa",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html
      lang="en"
      className={`${dmSans.variable} h-full antialiased`}
    >
      <head>
        <link rel="icon" href="/dulces-caprichos.jpg" />
      </head>
      <body className="min-h-full flex flex-col bg-rose-50!">
        <ContextLayout>
          <Header />
          <main>{children}</main>
          <Footer />
        </ContextLayout>
      </body>
    </html>
  );
}
